### ISSUE TITLE
While running the lambda -> save_configuration() takes exactly 4 arguments (6 given): TypeError

### ISSUE THREAD

**Issue by zerdush** [ocadotechnology/hippolyte#10]
We've got below exception:

save_configuration() takes exactly 4 arguments (6 given): TypeError
Traceback (most recent call last):
File "/var/task/hippolyte/dynamodb_backup.py", line 156, in lambda_handler
'region': _extract_from_arn(context.invoked_function_arn, 3)
File "/var/task/hippolyte/dynamodb_backup.py", line 101, in backup
kwargs['dynamodb_booster'].boost_throughput(pipeline_descriptions, MAX_DURATION_SINGLE_PIPELINE)
File "/var/task/hippolyte/dynamodb_booster.py", line 28, in boost_throughput
scaling_policies, scalable_targets)
TypeError: save_configuration() takes exactly 4 arguments (6 given)

Thanks

**Comment by RomekRJM** [comment]
Thanks for letting us know @zerdush. We have our private fork of this repository, where we are doing most of our development. I have made a mistake on last merge ( skipped changes from one file ), hence this problem. Let me know, if it works for you now.

**Comment by zerdush** [comment]
Thanks @RomekRJM, that works now.

**Comment by RomekRJM** [comment]
Cool, I'm closing this issue. Let us know if you have encounter other problems, we are eager to get more early adopters :)
